### ISSUE TITLE
Regarding scene_specific_fixes

### ISSUE THREAD

**Issue by ayushjain1144** [nihalsid/panoptic-lifting#7]
Hi, 

Thank you so much for your awesome work! We are trying to apply your method on some additional scenes from scannet and I was wondering how can we obtain `scene_specific_fixes` for those scenes? (My understanding is that these fixes are done by scannet themselves?) 

Any help regarding this and other things that we should keep in mind while evaluating your method on new scannet scenes would be very helpful!

**Comment by nihalsid** [comment]
Hi Ayush,

We perform the scene_specific_fixes to resolve ambiguous labels during evaluation. We noticed that for some scenes, the scannet labels were either ambiguous (which happens not only for scannet) or even incorrect (e.g. curtains being labeled as doors, couches labeled as tables, etc. in scannet) which influences the evaluation. Ideally we would have liked to reannotate the scene more carefully, since it's only 12 scenes. However, we were happy with just manually relabeling select instances, which is what "scene_specific_fixes" does. 

For new scenes, as long as you're not evaluating, this doesnt matter since the labels are used for nothing more than evaluation. If you are actually evaluating, then the thing to keep in mind is to look at the predictions as well as the ground truth and just check if the predictions are not being unjustly penalized as wrong when they are ambiguous. 

Let me know if this helps.
