### ISSUE TITLE
how to generate 3D semantic reconstruction in ".ply" ?

### ISSUE THREAD

**Issue by jinmaodaomaye2021** [nihalsid/panoptic-lifting#9]
Thanks for the great work. I am wondering how to generate the 3D semantic reconstruction in ".ply" ?
I mean the point clouds or the mesh representation of the scene with vertices colors representing the semantic labels.

**Comment by nihalsid** [comment]
Hi,

While the current code doesnt support this, you can do it by creating a grid of N^3 resolution in [-1, 1]^3 and querying the density (and thresholding upto some value) and semantics at each point, once the network is trained. Note that since it is nerf based geometry, this usually isnt quite perfect, and only makes sense when used with volumetric rendering
